### ISSUE TITLE
Particle value of 0% isn't preserved on game restart

### ISSUE THREAD

**Issue by geefr** [lolPants/Particular#1]
If I set the particle amounts to 0% in game then relaunch it resets to 100%

Any value other than zero works fine, guessing it's just the condition when reloading the settings

Minor annoyance/very low priority, otherwise works perfectly :)

**Comment by luludotdev** [comment]
Fixed as of lolPants/LibConf@6df8a94881ad51d4fcc91cecbdf566364045de2f
